apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-role
  namespace: production   # e.g. default or production
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get"]  # needed for rollout status
